[[setup-amplicode-studio]]
= Setup

[[system]]
== Check System Requirements

Make sure your computer meets the following requirements:

* 64-bit operating system: Windows, Linux or macOS.

* Memory – 16 GB is recommended.

* Hard drive free space – at least 20 GB.

[[studio]]
== Install Amplicode Studio

TODO

[[jdk]]
== Install Java Development Kit (JDK)

**TODO**

Download JDK version 17 (for example, https://adoptium.net[Eclipse Temurin^] or https://bell-sw.com/pages/downloads[Liberica^] JDK) and install it to a directory suggested by the installer. This is enough for creating and running applications from the IDE.

To run Amplicode applications from the terminal, set `JAVA_HOME` environment variable as described below.

* On *Windows*, create the `JAVA_HOME` variable with the path to the installed JDK root directory at *Computer* -> *Properties* -> *Advanced System Settings* -> *Advanced* -> *Environment variables*. The variable should be added to the *System variables* list.

* On *macOS* and *Linux* set `JAVA_HOME` in `~/.bash_profile` or another appropriate file of your shell, for example:
+
[source,bash]
----
export JAVA_HOME="/Library/Java/JavaVirtualMachines/liberica-jdk-17.jdk/Contents/Home"
----

* Restart the computer to make sure the environment variable has taken effect.

* Check correctness of the environment variable by running the following command in the console:
+
--

.On Windows
[source,bash]
----
"%JAVA_HOME%\bin\java" -version
----

.On Linux and macOS
[source,bash]
----
"$JAVA_HOME/bin/java" -version
----

The command should return the Java version, e.g. `17.0.6`.
--

CAUTION: If you connect to the internet via a proxy server, some Java system properties must be passed to the JVM running development tools and Gradle. xref:studio:install.adoc#working-behind-proxy[Configure] these properties using Jmix Studio.

[[Troubleshooting]]
== Troubleshooting

Depending on the size of your project, you may need to increase available memory for the IntelliJ IDEA and Gradle processes.

. In IntelliJ IDEA, open *Help -> Edit Custom VM Options...* and edit the `-Xmx` parameter (it's usually on top). The recommended value is `2048m` or more, for example:
+
[source,text]
----
-Xmx2048m
----

. Edit the `~/.gradle/gradle.properties` file and set the `-Xmx` parameter in the `org.gradle.jvmargs` property. The recommended value is `2048m` or more, for example:
+
[source,properties]
----
org.gradle.jvmargs=-Xmx2048m
----