= GraphQL Naming Rules

[[naming]]
== Naming
 . *_Field names_* should use `camelCase`. Many GraphQL clients are written in JavaScript, Java, Kotlin, or Swift, all of which recommend `camelCase` for variable names.
 . *_Type names_* should use `PascalCase`. This matches how classes are defined in the languages mentioned above.
 . *_Enum names_* should use `PascalCase`.
 . *_Enum values_* should use `ALL_CAPS` because they are similar to constants.
 . *_Mutations._* Name your mutations verb first. Then the object, or *_noun_*, if applicable. Use `camelCase`. A mutation represents an action so start with an action word that best describes what the mutation does.
 . *_Queries._* Use nouns for query names and `camelCase`. GraphQL is about asking for specific fields on objects, therefore it's essential that the query has exactly the same shape as the result. Naming queries the same as the type will help with that.
 . *_Queries._* Use postfix `List` for queries that return a collection of objects.

[[naming-examples]]
== Examples

[source, java]
----
type Query {
  //load Owner by ID
  owner(id: ID): OwnerDTO

  //load Owners list
  ownerList: [OwnerDTO]
}

type Mutation {
  //delete Owner by id
  deleteOwner(id: ID!): Void
  //update or create Owner
  updateOwner(input: OwnerInputDTO): OwnerDTO
  //custom business operation
  banOwner(id: ID!, reason: String): Void
}
----



