= ID Type

An ID scalar in a GraphQL schema is an indicator of a simple identifier.

In Amplicode, an ID scalar can correspond to one of the Java types, which are listed in the table below along with their representation in JSON and examples:

|===
|Java type	|JSON presentation	|JSON Sample
|java.lang.String	|An UTF‐8 string	|"uniquecode"
|java.lang.Integer	|An UTF-8 string	|"1"
|java.util.UUID	|An UTF‐8 string	|"4e083530-0b9c-11e1-9b41-6bdaa41bff94"
|java.lang.Long	|An UTF-8 string	|"123456"
|java.math.BigInteger	|An UTF-8 string	|"2147483647"
|===

To interact with a client, the ID scalar should be serialized as a string.

Examples of using ID scalars in the GraphQL schema:

+1.+ In a type declaration

[source, java]
    type OwnerDTO {
      id: ID
      address: String
      city: String
      email: String
      firstName: String
      lastName: String
      telephone: String
    }

In this case, the `id` field will be an identifier for `OwnerDTO`, since it has an `ID` type.

+2.+ In a query for loading an object by id

[source, java]
    "Query root"
    type Query {
      owner(id: ID!): OwnerDTO
    }

Technically, several ID fields can be declared for an object; in this case, the user has to select in the wizard, which field to use as the ID.

[[naming-convention]]
== React-admin Naming Convention

Each entity identifier used for creating React UI based on React-admin has to be named `id`. Therefore, if it is required to introduce or display a model object in a React UI, this object has to have its identifier attribute named `id`. Other names are not supported.

https://marmelab.com/react-admin/FAQ.html#can-i-have-custom-identifiersprimary-keys-for-my-resources[Can I have custom identifiers/primary keys for my resources? React-admin FAQ]

[[generating-schema]]
== Declaring the ID while generating the GraphQL schema
For Studio to use the ID type while generating the schema, it is necessary to mark the model attribute with one of the supported annotations. The annotations are:

 * `com.amplicode.core.graphql.annotation.GraphQLId`
 * `javax.persistence.Id`
 * `org.springframework.data.annotation.Id`
 * `org.mapstruct.Mapper` (when a DTO is used in the API, but Studio can trace the connection between the DTO and the entity).

[[query-id]]
=== Declaring an Argument as the ID
When Studio generates a method for a query/mutation in a GraphQL controller, where the `id` property is an argument, the developer has to add the  `com.amplicode.core.graphql.annotation.GraphQLId` annotation to the method's argument to ensure that Studio will treat this argument as identifier. This annotation means that this argument must have the `ID` type in the GraphQL schema.

[source, java]
    @MutationMapping(name = "deleteOwner")
    public void delete(@GraphQLId @Argument @NonNull Long id) {
        //
    }

When we have an array of identifiers (generic parameters) as an argument, the declaration looks as in the following example:

[source, java]
    @MutationMapping(name = "cancelManyOwner")
    public void cancelMany(@Argument List<@GraphQLId Long> ids) {
        // ...
    }

Schema:
[source, java]
    cancelManyOwner(ids: [ID]) Void


[[return-id]]
=== Declaring the ID for the Returned Object
If a method in a Spring for GraphQL controller the returned object is marked with the `com.amplicode.core.graphql.annotation.GraphQLId` annotation, the type of the returned object (for query/mutation) should be `ID` in the schema.

*Declaration:*
[source, java]
    @GraphQLId
    @QueryMapping(DefaultOwnerId)
    public String getDefaultOwnerId() {
        //...
    }


*Schema:*
[source, java]
    defaultOwnerId: ID

[[id-type]]
=== Declaring the ID Attribute for a Type
The source of the GraphQL type at the time of schema generation can be:

. an Entity (JPA/Mongo/Redis)
. a DTO.

If a field belonging to the DTO or Entity complies with the `Id` property condition, this field will have the `ID` type in the GraphQL schema.

[[jpa]]
=== JPA

There are four ways to declare that an attribute of an object belonging to a GraphQL API is an identifier

* `javax.persistence.Id` (for JPA entities)
* `org.springframework.data.annotation.Id` (any classes)
* `com.amplicode.core.graphql.annotation.GraphQLId` (any classes)
* DTO: if Studio can determine that the DTO class is related to an entity that has a declared ID, it will be regarded as an ID in the DTO as well.

[[declaring-connection]]
==== Declaring the Connection Between the DTO and the Entity

Connection between the DTO and the Entity should be defined implicitly, assuming that *_MapStruct_* is used in the project, meaning that in the interface or abstract class annotated  `org.mapstruct.Mapper`, there should be a method that defines the connection, example:

[source, java]
@Mapper(componentModel = "spring")
public interface PetMapper {
   PetDTO petToDTO(Pet pet);
}

In this case the attribute marked as `Id` in the entity will be perceived as an attribute marked as `Id` in the DTO as well.

[NOTE]
The connection doesn't have to be established through a mapper; it can also be done via a special `@link` comment.


